### ISSUE TITLE
order of clinics

### ISSUE THREAD

**Issue by mvasin** [jakubboucek/schedule-reception-doctors#1]
Hi Jakub! Huge thanks!

Can you please make the clinics show in order specified in `ids` array?

**Comment by jakubboucek** [comment]
Do you mean remove [intentional department sorting](https://github.com/jakubboucek/schedule-reception-doctors/blob/master/source/app.js#L19)? It was in origin code.

**Comment by mvasin** [comment]
Yeah, let's remove it.
