### ISSUE TITLE
Content being cut

### ISSUE THREAD

**Issue by mvasin** [jakubboucek/schedule-reception-doctors#7]
@jakubboucek Here's the iconBIT screen after you deployed the latest "no departments cut" revision:

![img_3766](https://cloud.githubusercontent.com/assets/12434833/23654159/74a90970-0340-11e7-9c82-34f2e67ca4f4.JPG)

At the bottom of the page, department starts, then table header, then cut. :(

**Comment by jakubboucek** [comment]
Same bug as #5
